/**
 * Phase 2 AI feature: a targeted, on-demand hint generated by Firebase AI Logic
 * (Gemini). It is grounded in the lesson's structured step state — never raw
 * page text — and is explicitly instructed to nudge without revealing the
 * answer. The MVP works fully with AI off: callers must treat this as a
 * best-effort enhancement and fall back to the hand-written static hint on any
 * failure (no config, network error, timeout, or an answer-leaking response).
 */
import { getAI, getGenerativeModel, GoogleAIBackend, type GenerativeModel } from 'firebase/ai'
import { getFirebaseApp, isFirebaseConfigured } from '../lib/firebase'
import { computeGroundTruth, verifyHintIsSafe } from '../lib/mathEngine'
import type { LessonStep } from '../types/lesson'

export interface HintContext {
  /** The exact problem prompt shown to the learner. */
  prompt: string
  /** Human-readable concept/skill, e.g. "translate-by". */
  concept: string
  /** The correct answer — sent ONLY so the model avoids revealing it. */
  answer: string
  /** The hand-written fallback hint (and a style reference for the model). */
  staticHint: string
  /** What the learner has entered/attempted so far, if known. */
  attempt?: string
  /**
   * The active step. When present, the math engine recomputes the canonical
   * answer to ground the prompt and verifies the AI response against the
   * subject's logic so it can never state wrong math.
   */
  step?: LessonStep
  /**
   * Escalation level of the hint. 'guiding' asks for a more specific, step-by-step
   * nudge than the first 'general' hint — used when the learner is still stuck
   * after an earlier hint and a wrong attempt. Still never reveals the answer.
   */
  escalation?: 'general' | 'guiding'
}

const SYSTEM_INSTRUCTION = [
  'You are a patient coordinate-geometry tutor for 9th-grade students learning graph',
  'transformations and coordinate translations.',
  'Give exactly ONE short hint (one or two sentences, under 30 words).',
  'Nudge the student toward the NEXT step in their reasoning.',
  'NEVER state the final answer, the target coordinates, or the exact numbers',
  'that solve the problem. Do not do the arithmetic for them.',
  'Be concrete, encouraging, and focused on direction and sign when relevant.',
  'Return only the hint text, with no preamble or quotation marks.',
].join(' ')

let cachedModel: GenerativeModel | null = null

function getModel(): GenerativeModel {
  if (!cachedModel) {
    const ai = getAI(getFirebaseApp(), { backend: new GoogleAIBackend() })
    cachedModel = getGenerativeModel(ai, {
      model: 'gemini-2.5-flash-lite',
      systemInstruction: SYSTEM_INSTRUCTION,
      generationConfig: {
        temperature: 0.4,
        topP: 0.9,
        topK: 40,
        maxOutputTokens: 120,
      },
    })
  }
  return cachedModel
}

/**
 * localStorage key for a runtime override of the AI-hint flag. This lets the app
 * flip AI on/off *on screen* (Settings page) without an env change or rebuild —
 * handy for demoing that the MVP teaches fully with AI turned off. The override,
 * when present, takes precedence over the build-time env var below.
 */
const AI_HINTS_OVERRIDE_KEY = 'ai-hints-enabled'

/** Read the runtime override: true/false if set by the user, else null. */
export function getAiHintOverride(): boolean | null {
  try {
    const raw = localStorage.getItem(AI_HINTS_OVERRIDE_KEY)
    if (raw === 'true') return true
    if (raw === 'false') return false
    return null
  } catch {
    return null
  }
}

/** Set (true/false) or clear (null) the runtime override. Safe if storage is unavailable. */
export function setAiHintOverride(value: boolean | null): void {
  try {
    if (value === null) localStorage.removeItem(AI_HINTS_OVERRIDE_KEY)
    else localStorage.setItem(AI_HINTS_OVERRIDE_KEY, value ? 'true' : 'false')
  } catch {
    // Ignore: storage being unavailable just means no override (env wins).
  }
}

/** The build-time default from the env var (unset/empty/true = on). */
function envAiHintEnabled(): boolean {
  const flag = import.meta.env.VITE_AI_HINTS_ENABLED
  if (flag === undefined || flag === null || flag === '') return true
  const value = String(flag).trim().toLowerCase()
  return !(value === 'false' || value === '0' || value === 'off' || value === 'no')
}

/**
 * Phase 1 feature flag. AI hints are an *enhancement* on top of the MVP, so the
 * whole AI layer can be turned off explicitly. Resolution order:
 *   1. The runtime override (Settings toggle / localStorage), if the user set one.
 *   2. Otherwise the build-time `VITE_AI_HINTS_ENABLED` env var (default on).
 * With it off, the escalating-hint ladder runs entirely on deterministic fallbacks.
 */
export function isAiHintFlagEnabled(): boolean {
  const override = getAiHintOverride()
  if (override !== null) return override
  return envAiHintEnabled()
}

/**
 * Whether the smarter-hint feature can run: the Phase 1 feature flag must be on
 * AND the Firebase web config must be present. Either being absent disables AI
 * and callers fall back to the hand-written static hints.
 */
export function isAiHintAvailable(): boolean {
  return isAiHintFlagEnabled() && isFirebaseConfigured()
}

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((_, reject) => setTimeout(() => reject(new Error('AI hint timed out')), ms)),
  ])
}

function normalize(value: string): string {
  return value.toLowerCase().replace(/\s+/g, '').replace(/[()]/g, '')
}

/** True if the model accidentally revealed the literal answer. */
function leaksAnswer(text: string, answer: string): boolean {
  const a = normalize(answer)
  return a.length >= 2 && normalize(text).includes(a)
}

/**
 * Fetch a targeted hint. Resolves to a hint string, or throws on any failure so
 * the caller can fall back to the static hint. The response is verified against
 * the known answer so the AI can never hand over the solution.
 */
export async function fetchTargetedHint(ctx: HintContext): Promise<string> {
  if (!isAiHintAvailable()) throw new Error('AI hint unavailable')

  // Ground the prompt in the engine's canonical answer when a step is supplied,
  // so the model is anchored to the real solution rather than the caller's
  // best-effort string. Falls back to the provided answer if there's no step.
  const groundedAnswer = ctx.step ? computeGroundTruth(ctx.step).text || ctx.answer : ctx.answer

  const escalationLine =
    ctx.escalation === 'guiding'
      ? 'The student already saw a first hint and is still stuck. Give a more specific, step-by-step nudge — name the exact next move to consider — but still do NOT reveal the final answer or its numbers.'
      : 'Give a gentle first nudge toward the next step.'

  const userPrompt = [
    `Problem: ${ctx.prompt}`,
    `Concept: ${ctx.concept}`,
    `Correct answer (for your reference only — DO NOT reveal it): ${groundedAnswer}`,
    ctx.attempt ? `Student's attempt so far: ${ctx.attempt}` : 'The student has not answered yet.',
    `A hand-written hint for style reference: ${ctx.staticHint}`,
    escalationLine,
    'Now write one fresh hint that guides without giving the answer away.',
  ].join('\n')

  const result = await withTimeout(getModel().generateContent(userPrompt), 8000)
  const text = result.response.text().trim()

  if (!text || leaksAnswer(text, groundedAnswer)) {
    throw new Error('AI hint rejected (empty or leaked the answer)')
  }

  // Additional engine guard: reject hints that leak the answer or assert false
  // math against the subject's logic, so the AI can never present wrong numbers.
  if (ctx.step && !verifyHintIsSafe(text, ctx.step)) {
    throw new Error('AI hint rejected (failed math-engine verification)')
  }

  return text
}
