import type { Lesson } from '../../types/lesson'

export const linearEquationsLesson: Lesson = {
  id: 'linear-equations',
  title: 'Linear Equations & Graphs',
  description:
    'Solve one-variable equations, then graph lines with slope and intercept.',
  subject: 'Linear Equations & Inequalities',
  order: 2,
  region: 'Linear Mountain',
  icon: '⛰️',
  estimatedMinutes: 12,
  steps: [
    {
      id: 'conf-1',
      type: 'confidence',
      title: 'Quick check',
      question: 'Have you solved equations like 2x + 3 = 11 before?',
    },
    {
      id: 'explore-numberline',
      type: 'number-line',
      title: 'Explore: moving on a number line',
      prompt:
        'Before equations, get a feel for adding and subtracting. Start at 3 and move so you land on −2. (That is the same as adding −5.)',
      start: 3,
      target: -2,
      min: -6,
      max: 6,
      insight: 'Notice: moving left is just adding a negative — every step left is −1.',
      why: 'Moving from 3 down to −2 is a change of −5: 3 + (−5) = −2.',
      hint: 'Each step left subtracts 1. How many steps from 3 to −2?',
    },
    {
      id: 'predict-balance',
      type: 'multiple-choice',
      title: 'Predict first',
      prompt:
        "You're about to balance 2x + 4 = 10 on a scale. If you remove 4 from only the left side, what do you think happens?",
      options: [
        'The scale tips — it is no longer balanced',
        'Nothing — it stays balanced',
        'x instantly becomes 10',
      ],
      correctIndex: 0,
      insight: 'Whatever you do to one side, you must do to the other. That single rule solves every linear equation.',
      why: 'Removing from just one side breaks the balance. To keep it level you must do the same thing to both sides — that is the whole trick to solving equations. Try it on the next screen.',
      hint: 'A scale only stays level if both pans change by the same amount.',
    },
    {
      id: 'balance-explore',
      type: 'balance-scale',
      title: 'Discover: keep the scale balanced',
      prompt:
        'This scale shows 2x + 4 = 10. Remove the same amount from both sides, then split evenly, and watch what x must be.',
      coeff: 2,
      constant: 4,
      total: 10,
      insight: 'Same move on both sides, every time: subtract to clear the extras, then divide to split x. The balance never breaks.',
      why: 'Subtract 4 from both sides: 2x = 6. Divide both sides by 2: x = 3.',
      hint: 'First subtract the 4 unit-blocks from both sides, then divide both sides by 2.',
    },
    {
      id: 'concept-solve',
      type: 'concept',
      title: 'Why that works',
      body:
        'Removing the same amount from both sides keeps an equation balanced — just like a scale. To solve a linear equation, undo what was done to x: subtract or add to move constants, then divide to isolate x. For 2x + 3 = 11: subtract 3 to get 2x = 8, then divide by 2 to get x = 4.',
    },
    {
      id: 'solve-1',
      type: 'balance-scale',
      title: 'Solve for x',
      prompt:
        'Solve 2x + 3 = 11 on the scale. Subtract from both sides to clear the units, then divide both sides to find x.',
      coeff: 2,
      constant: 3,
      total: 11,
      insight: 'Undo in reverse order: the +3 comes off first, then undo the ×2 by dividing. The scale stays level the whole time.',
      why: 'Subtract 3 from both sides: 2x = 8. Divide both sides by 2: x = 4.',
      hint: 'First subtract the 3 unit-blocks from both sides, then divide both sides by 2.',
      variants: [
        {
          id: 'solve-1-v1',
          type: 'balance-scale',
          title: 'Solve for x',
          prompt: 'Solve 4x + 2 = 14. Subtract from both sides, then divide both sides.',
          coeff: 4,
          constant: 2,
          total: 14,
          why: 'Subtract 2 from both sides: 4x = 12. Divide both sides by 4: x = 3.',
          hint: 'Clear the 2 units from both sides first, then divide both sides by 4.',
        },
        {
          id: 'solve-1-v2',
          type: 'balance-scale',
          title: 'Solve for x',
          prompt: 'Solve 2x + 5 = 13. Same two moves: clear the units, then split evenly.',
          coeff: 2,
          constant: 5,
          total: 13,
          why: 'Subtract 5 from both sides: 2x = 8. Divide both sides by 2: x = 4.',
          hint: 'Subtract the 5 units from both sides, then divide both sides by 2.',
        },
        {
          id: 'solve-1-v3',
          type: 'balance-scale',
          title: 'Solve for x',
          prompt: 'Solve 3x + 4 = 13. Clear the units from both sides, then divide into 3.',
          coeff: 3,
          constant: 4,
          total: 13,
          why: 'Subtract 4 from both sides: 3x = 9. Divide both sides by 3: x = 3.',
          hint: 'Subtract the 4 units from both sides, then divide both sides by 3.',
        },
      ],
      remediation: {
        title: "Let's master two-step equations",
        body:
          'A two-step equation like 2x + 3 = 11 was built by doing two things to x: first multiplying by a number, then adding a constant. To solve it, undo those steps in reverse order. First undo the addition by subtracting the constant from BOTH sides. Then undo the multiplication by dividing BOTH sides by the number in front of x. Whatever you do to one side you must do to the other — that keeps the scale balanced.',
        tips: [
          'Always deal with the lone "+" or "−" number first, then the number multiplying x.',
          'Do the exact same operation to both sides every single time.',
          'Check your answer: plug x back into the original equation and make sure both sides match.',
          'Subtraction undoes addition; division undoes multiplication.',
        ],
      },
    },
    {
      id: 'solve-2',
      type: 'balance-scale',
      title: 'One more',
      prompt:
        'Now balance 3x + 2 = 11. Same moves: clear the units from both sides, then split evenly into 3.',
      coeff: 3,
      constant: 2,
      total: 11,
      insight: 'Same two moves, new numbers — clear the constant, then divide. The recipe never changes.',
      why: 'Subtract 2 from both sides: 3x = 9. Divide both sides by 3: x = 3.',
      hint: 'Subtract the 2 unit-blocks from both sides first, then divide both sides by 3.',
      variants: [
        {
          id: 'solve-2-v1',
          type: 'balance-scale',
          title: 'One more',
          prompt: 'Balance 4x + 3 = 15. Clear the units from both sides, then divide into 4.',
          coeff: 4,
          constant: 3,
          total: 15,
          why: 'Subtract 3 from both sides: 4x = 12. Divide both sides by 4: x = 3.',
          hint: 'Subtract the 3 units from both sides, then divide both sides by 4.',
        },
        {
          id: 'solve-2-v2',
          type: 'balance-scale',
          title: 'One more',
          prompt: 'Balance 2x + 6 = 12. Clear the units from both sides, then divide into 2.',
          coeff: 2,
          constant: 6,
          total: 12,
          why: 'Subtract 6 from both sides: 2x = 6. Divide both sides by 2: x = 3.',
          hint: 'Subtract the 6 units from both sides, then divide both sides by 2.',
        },
        {
          id: 'solve-2-v3',
          type: 'balance-scale',
          title: 'One more',
          prompt: 'Balance 5x + 2 = 17. Clear the units from both sides, then divide into 5.',
          coeff: 5,
          constant: 2,
          total: 17,
          why: 'Subtract 2 from both sides: 5x = 15. Divide both sides by 5: x = 3.',
          hint: 'Subtract the 2 units from both sides, then divide both sides by 5.',
        },
      ],
      remediation: {
        title: 'Solving equations, step by step',
        body:
          'Every equation of the form ax + b = c follows the same recipe. Step 1: move the constant b across by subtracting it from both sides, leaving ax on its own. Step 2: divide both sides by a (the number multiplying x) to get x by itself. The order matters — clear the added/subtracted number BEFORE you divide, otherwise you have to divide every term.',
        tips: [
          'Write the equation, then subtract the constant from both sides on the next line.',
          'Then divide both sides by the coefficient of x.',
          'Keep both sides lined up so you never forget to do a move to both.',
          'Plug your answer back in to confirm the two sides are equal.',
        ],
      },
    },
    {
      id: 'predict-slope',
      type: 'multiple-choice',
      title: 'Predict first',
      prompt:
        "Next you'll drag one end of a line to make it steeper. As it gets steeper, what do you think happens to the rise ÷ run number below it?",
      options: ['It gets bigger', 'It gets smaller', 'It stays the same'],
      correctIndex: 0,
      insight: 'Steeper line, bigger rise ÷ run. Keep an eye on that number as you drag next.',
      why: 'A steeper line climbs more for the same run, so rise ÷ run grows. You are about to watch it happen.',
      hint: 'Steeper means more vertical climb for each step to the right.',
    },
    {
      id: 'slope-discovery-1',
      type: 'slope-discovery',
      title: 'Discover: what makes a line steep?',
      prompt:
        'One end of this line is pinned at the origin. Drag the other end around. Watch the number that appears below — what do you think it measures? Then dial it until it reads exactly 2.',
      fixed: [0, 0],
      movable: [3, 0],
      targetSlope: 2,
      insight: 'Double the rise and the number doubles too. That number is how much y changes for each step in x.',
      why: 'The number is rise ÷ run — it grows as the line gets steeper. Climbing to (1, 2) or (2, 4) gives 2 ÷ 1 = 2.',
      hint: 'Rise ÷ run must equal 2. Try rising 2 for every 1 step right, like the point (1, 2).',
    },
    {
      id: 'concept-graph',
      type: 'concept',
      title: 'Now it has a name: slope',
      body:
        'That number you just dialed in has a name: the slope, written m. It measures steepness as rise ÷ run — bigger number, steeper line. Every line can be written y = mx + b, where b is the y-intercept: where the line crosses the y-axis. The line below is y = 2x + 1 — slope 2 (rises 2 for every 1 right), crossing the y-axis at 1.',
      graph: {
        lines: [{ m: 2, b: 1, color: '#38bdf8', label: 'y = 2x + 1' }],
        points: [{ x: 0, y: 1, color: '#fbbf24', label: 'b = 1' }],
      },
    },
    {
      id: 'mc-slope',
      type: 'multiple-choice',
      title: 'Spot the slope',
      prompt: 'You named it above. In the equation y = 3x − 2, what is the slope?',
      options: ['3', '−2', 'x', '1'],
      correctIndex: 0,
      insight: 'The number stuck to x is always the slope — you can read it straight off the equation, no graph needed.',
      why: 'In y = mx + b, the slope m is the number multiplying x, which is 3.',
      hint: 'The slope is the number multiplying x — the same rise ÷ run you discovered.',
      variants: [
        {
          id: 'mc-slope-v1',
          type: 'multiple-choice',
          title: 'Spot the slope',
          prompt: 'In the equation y = 5x + 4, what is the slope?',
          options: ['4', '5', 'x', '−5'],
          correctIndex: 1,
          why: 'In y = mx + b, the slope m is the number multiplying x, which is 5.',
          hint: 'Find the number multiplying x — ignore the constant on its own.',
        },
        {
          id: 'mc-slope-v2',
          type: 'multiple-choice',
          title: 'Spot the slope',
          prompt: 'In the equation y = −2x + 7, what is the slope?',
          options: ['7', '2', '−2', 'x'],
          correctIndex: 2,
          why: 'The number multiplying x is −2 (keep the negative sign), so the slope is −2.',
          hint: 'The slope is the coefficient of x — and it carries its sign with it.',
        },
        {
          id: 'mc-slope-v3',
          type: 'multiple-choice',
          title: 'Spot the slope',
          prompt: 'In the equation y = x − 6, what is the slope?',
          options: ['−6', '1', '6', 'x'],
          correctIndex: 1,
          why: 'A bare x means 1x, so the slope is 1.',
          hint: 'When you see just "x" with no number, the hidden coefficient is 1.',
        },
      ],
      remediation: {
        title: 'Reading slope from y = mx + b',
        body:
          'Any line written as y = mx + b hands you its slope and y-intercept directly: m (the number multiplying x) is the slope, and b (the constant on its own) is the y-intercept. To spot the slope, find the number attached to x — and keep its sign. Two traps: a negative like −2x has slope −2 (not 2), and a bare x means 1x, so the slope is 1.',
        graph: {
          lines: [{ m: 3, b: -2, color: '#38bdf8', label: 'y = 3x − 2' }],
        },
        tips: [
          'Slope is always the number multiplying x — never the constant by itself.',
          'A minus sign in front of x is part of the slope: −2x → slope −2.',
          'A lone x (or −x) hides a 1: slope 1 (or −1).',
          'The leftover number with no x is the y-intercept, not the slope.',
        ],
      },
    },
    {
      id: 'line-build-1',
      type: 'line-builder',
      title: 'Build the line',
      prompt:
        'Now use the Slope and Intercept buttons to build y = 2x + 1 so it matches the dashed target.',
      target: { m: 2, b: 1 },
      start: { m: 0, b: 0 },
      insight: 'Slope tilts the line; intercept slides it up and down. Just two numbers describe any line.',
      why: 'A slope of 2 makes the line rise 2 per step right; an intercept of 1 lifts it to cross the y-axis at 1.',
      hint: 'Raise the slope to 2 so the line tilts up, then raise the intercept to 1.',
      variants: [
        {
          id: 'line-build-1-v1',
          type: 'line-builder',
          title: 'Build the line',
          prompt: 'Build y = 3x − 2 so it matches the dashed target.',
          target: { m: 3, b: -2 },
          start: { m: 0, b: 0 },
          why: 'Slope 3 tilts the line up steeply; an intercept of −2 drops it to cross the y-axis at −2.',
          hint: 'Raise the slope to 3, then lower the intercept to −2.',
        },
        {
          id: 'line-build-1-v2',
          type: 'line-builder',
          title: 'Build the line',
          prompt: 'Build y = −1x + 3 so it matches the dashed target.',
          target: { m: -1, b: 3 },
          start: { m: 0, b: 0 },
          why: 'A slope of −1 tilts the line down; an intercept of 3 lifts it to cross the y-axis at 3.',
          hint: 'Lower the slope to −1 so the line tilts down, then raise the intercept to 3.',
        },
      ],
      remediation: {
        title: 'Building a line from m and b',
        body:
          'In y = mx + b the two numbers control two different things. The slope m sets the tilt: a bigger m is steeper, and a negative m tilts the line downhill. The intercept b slides the whole line up or down so it crosses the y-axis at b. Set the slope first to get the tilt right, then adjust the intercept to slide it into place.',
        tips: [
          'Set the slope first (the tilt), then the intercept (the height).',
          'Positive slope goes uphill ↗, negative slope goes downhill ↘.',
          'The intercept is exactly where the line crosses the y-axis.',
          'Match the dashed target: same tilt and same crossing point.',
        ],
      },
    },
    {
      id: 'word-1',
      type: 'move-point',
      title: 'Real-world line',
      prompt:
        'A candle is 6 cm tall and burns down 1 cm each hour, so its height is y = −x + 6. Drag the point onto the dashed line to show the candle’s height after 4 hours (x = 4).',
      start: [0, 6],
      target: [4, 2],
      line: { m: -1, b: 6 },
      lineLabel: 'y = −x + 6',
      insight: 'At x = 4 the line gives y = 2 — the candle is 2 cm tall. Reading a real-world line is just substituting the input.',
      why: 'y = −(4) + 6 = 2, so after 4 hours the candle is 2 cm tall — the point (4, 2).',
      hint: 'Move right to x = 4, then up or down until the point sits exactly on the dashed line.',
      variants: [
        {
          id: 'word-1-v1',
          type: 'move-point',
          title: 'Real-world line',
          prompt:
            'A tank holds 5 L and drains 1 L per minute: y = −x + 5. Drag the point onto the line to show the amount left after 3 minutes (x = 3).',
          start: [0, 5],
          target: [3, 2],
          line: { m: -1, b: 5 },
          lineLabel: 'y = −x + 5',
          why: 'y = −(3) + 5 = 2, so 2 L are left after 3 minutes — the point (3, 2).',
          hint: 'Move right to x = 3, then down onto the dashed line.',
        },
        {
          id: 'word-1-v2',
          type: 'move-point',
          title: 'Real-world line',
          prompt:
            'A plant is 2 cm tall and grows 1 cm per week: y = x + 2. Drag the point onto the line to show its height after 3 weeks (x = 3).',
          start: [0, 2],
          target: [3, 5],
          line: { m: 1, b: 2 },
          lineLabel: 'y = x + 2',
          why: 'y = (3) + 2 = 5, so the plant is 5 cm tall after 3 weeks — the point (3, 5).',
          hint: 'Move right to x = 3, then up onto the dashed line.',
        },
      ],
      remediation: {
        title: 'Reading a value off a real-world line',
        body:
          'A real-world line like y = −x + 6 is a rule connecting an input (x, often time) to an output (y, often a height or amount). To find the output at a given moment, substitute that x-value into the rule and compute y. On the graph, that means moving across to your x-value and then up or down until you land exactly on the line — the y-coordinate there is your answer.',
        tips: [
          'Identify what x and y stand for in the story (time vs. amount).',
          'Substitute the given x into y = mx + b and do the arithmetic.',
          'On the graph: go across to x first, then onto the line to read y.',
          'A negative slope means the quantity is shrinking; positive means it is growing.',
        ],
      },
    },
    {
      id: 'complete',
      type: 'complete',
      title: 'Lesson complete!',
      message:
        'You solved linear equations and built a line from its slope and intercept.',
      discovery:
        'Doing the same thing to both sides keeps an equation balanced — and a line is fully described by its slope and intercept.',
    },
  ],
  lessonCheck: [
    {
      id: 'lc-1',
      title: 'Question 1 of 3',
      prompt: 'Solve: 4x + 1 = 13. What is x?',
      answers: ['3', 'x=3'],
      hint: 'Subtract 1, then divide by 4.',
      why: '4x = 12, so x = 3.',
      variants: [
        {
          prompt: 'Solve: 3x + 2 = 17. What is x?',
          answers: ['5', 'x=5'],
          hint: 'Subtract 2 from both sides, then divide by 3.',
          why: '3x = 15, so x = 5.',
        },
        {
          prompt: 'Solve: 5x − 4 = 11. What is x?',
          answers: ['3', 'x=3'],
          hint: 'Add 4 to both sides first, then divide by 5.',
          why: '5x = 15, so x = 3.',
        },
      ],
    },
    {
      id: 'lc-2',
      title: 'Question 2 of 3',
      prompt: 'In y = −2x + 5, what is the y-intercept?',
      answers: ['5'],
      hint: 'The y-intercept is b in y = mx + b.',
      why: 'b = 5, so the line crosses the y-axis at 5.',
      variants: [
        {
          prompt: 'In y = 3x − 7, what is the y-intercept?',
          answers: ['-7', '−7'],
          hint: 'The y-intercept is the constant b, including its sign.',
          why: 'b = −7, so the line crosses the y-axis at −7.',
        },
        {
          prompt: 'In y = −x + 2, what is the slope?',
          answers: ['-1', '−1'],
          hint: 'The slope is m, the number multiplying x. −x means −1x.',
          why: 'The coefficient of x is −1, so the slope is −1.',
        },
      ],
    },
    {
      id: 'lc-3',
      title: 'Question 3 of 3',
      prompt:
        'A gym charges $20 to join plus $10 per month (y = 10x + 20). What is the total after 4 months?',
      answers: ['60', '$60'],
      hint: 'Substitute x = 4 into y = 10x + 20.',
      why: 'y = 10(4) + 20 = 40 + 20 = 60 dollars.',
      variants: [
        {
          prompt:
            'A plan costs $15 to start plus $5 per month (y = 5x + 15). What is the total after 6 months?',
          answers: ['45', '$45'],
          hint: 'Substitute x = 6 into y = 5x + 15.',
          why: 'y = 5(6) + 15 = 30 + 15 = 45 dollars.',
        },
        {
          prompt:
            'A taxi charges $3 to start plus $2 per mile (y = 2x + 3). What is the cost after 7 miles?',
          answers: ['17', '$17'],
          hint: 'Substitute x = 7 into y = 2x + 3.',
          why: 'y = 2(7) + 3 = 14 + 3 = 17 dollars.',
        },
      ],
    },
  ],
  practiceSteps: [
    {
      id: 'p-solve',
      type: 'balance-scale',
      title: 'Practice: Balance to solve',
      prompt:
        'Solve 3x + 3 = 12 on the scale. Clear the units from both sides, then divide both sides by 3.',
      coeff: 3,
      constant: 3,
      total: 12,
      why: 'Subtract 3 from both sides: 3x = 9. Divide both sides by 3: x = 3.',
      hint: 'Subtract the 3 unit-blocks from both sides, then divide both sides by 3.',
    },
    {
      id: 'p-line',
      type: 'line-builder',
      title: 'Practice: Build the line',
      prompt: 'Build the line y = −1x + 2 to match the target.',
      target: { m: -1, b: 2 },
      start: { m: 0, b: 0 },
      why: 'A slope of −1 tilts the line down; an intercept of 2 lifts it to cross at 2.',
      hint: 'Lower the slope below zero, then raise the intercept to 2.',
    },
    {
      id: 'p-mc',
      type: 'multiple-choice',
      title: 'Practice: Slope',
      prompt: 'What is the slope of y = −4x + 1?',
      options: ['−4', '1', '4', 'x'],
      correctIndex: 0,
      why: 'The coefficient of x is −4.',
      hint: 'Look at the number multiplying x.',
    },
  ],
}
