import type { Lesson } from '../../types/lesson'

export const quadraticsLesson: Lesson = {
  id: 'quadratics',
  title: 'Quadratic Equations & Parabolas',
  description:
    'Graph parabolas, find the vertex and axis of symmetry, and solve by factoring.',
  subject: 'Quadratic Equations',
  order: 5,
  region: 'Parabola Peaks',
  icon: '🏔️',
  estimatedMinutes: 12,
  steps: [
    {
      id: 'conf-1',
      type: 'confidence',
      title: 'Quick check',
      question: 'Have you graphed a parabola or factored x² + 5x + 6 before?',
    },
    {
      id: 'concept-form',
      type: 'concept',
      title: 'Vertex form',
      body:
        'A quadratic in vertex form is y = a(x − h)² + k. Its graph is a parabola whose turning point (vertex) is at (h, k). If a > 0 it opens up; if a < 0 it opens down. The parabola below is y = (x − 1)² − 2, with vertex (1, −2).',
      graph: {
        parabolas: [{ h: 1, k: -2, a: 1, color: '#f97316' }],
        points: [{ x: 1, y: -2, color: '#fbbf24', label: 'vertex (1, −2)' }],
      },
    },
    {
      id: 'vertex-1',
      type: 'find-vertex',
      title: 'Find the vertex',
      prompt: 'This graph shows y = (x − 1)² − 2. Drag the dot to the vertex.',
      h: 1,
      k: -2,
      a: 1,
      xMin: -3,
      xMax: 5,
      why: 'In y = (x − 1)² − 2, h = 1 and k = −2, so the vertex is (1, −2).',
      hint: 'The vertex is the lowest point of this upward parabola.',
    },
    {
      id: 'concept-axis',
      type: 'concept',
      title: 'Axis of symmetry',
      body:
        'Every parabola is symmetric about a vertical line through its vertex, called the axis of symmetry. Its equation is x = h. For y = (x − 3)² + 1, the axis of symmetry is x = 3.',
    },
    {
      id: 'axis-1',
      type: 'number-input',
      title: 'Axis of symmetry',
      prompt: 'What is the axis of symmetry of y = (x − 3)² + 1? Enter the value of x.',
      answers: ['3', 'x=3'],
      inputLabel: 'x =',
      why: 'The axis of symmetry is x = h, and here h = 3.',
      hint: 'The axis passes through the vertex at x = h.',
    },
    {
      id: 'concept-factor',
      type: 'concept',
      title: 'Solving by factoring',
      body:
        'To solve x² − 5x + 6 = 0, factor it into (x − 2)(x − 3) = 0. A product is zero only if a factor is zero, so x = 2 or x = 3. These are the x-intercepts of the parabola.',
    },
    {
      id: 'mc-roots',
      type: 'multiple-choice',
      title: 'Find the roots',
      prompt: 'What are the solutions of x² − 5x + 6 = 0?',
      options: ['x = 2 and x = 3', 'x = −2 and x = −3', 'x = 1 and x = 6', 'x = 5 and x = 6'],
      correctIndex: 0,
      why: 'It factors as (x − 2)(x − 3) = 0, so x = 2 or x = 3.',
      hint: 'Find two numbers that multiply to 6 and add to 5.',
    },
    {
      id: 'solve-1',
      type: 'number-input',
      title: 'Solve a simple quadratic',
      prompt: 'Solve x² − 9 = 0. Enter the positive solution.',
      answers: ['3', 'x=3'],
      inputLabel: 'x =',
      why: 'x² = 9 so x = 3 or x = −3. The positive solution is 3.',
      hint: 'Add 9 to both sides, then take the square root.',
    },
    {
      id: 'complete',
      type: 'complete',
      title: 'Lesson complete!',
      message: 'You found vertices, axes of symmetry, and solved quadratics by factoring.',
      discovery:
        'Vertex form y = a(x − h)² + k hands you the turning point (h, k) and the axis of symmetry x = h directly.',
    },
  ],
  lessonCheck: [
    {
      id: 'lc-1',
      title: 'Question 1 of 3',
      prompt: 'What is the vertex of y = (x + 2)² − 5? Enter as (x, y).',
      answers: ['(-2, -5)', '-2,-5'],
      hint: 'Vertex form y = a(x − h)² + k has vertex (h, k); here x + 2 means h = −2.',
      why: 'h = −2 and k = −5, so the vertex is (−2, −5).',
      variants: [
        {
          prompt: 'What is the vertex of y = (x − 1)² + 3? Enter as (x, y).',
          answers: ['(1, 3)', '1,3'],
          hint: 'x − 1 means h = 1; k is the value added at the end.',
          why: 'h = 1 and k = 3, so the vertex is (1, 3).',
        },
        {
          prompt: 'What is the vertex of y = (x + 5)² − 2? Enter as (x, y).',
          answers: ['(-5, -2)', '-5,-2'],
          hint: 'x + 5 is x − (−5), so h = −5.',
          why: 'h = −5 and k = −2, so the vertex is (−5, −2).',
        },
      ],
    },
    {
      id: 'lc-2',
      title: 'Question 2 of 3',
      prompt: 'What is the axis of symmetry of y = (x − 4)² + 2? Enter the value of x.',
      answers: ['4', 'x=4'],
      hint: 'The axis of symmetry is x = h.',
      why: 'h = 4, so the axis of symmetry is x = 4.',
      variants: [
        {
          prompt: 'What is the axis of symmetry of y = (x + 3)² − 1? Enter the value of x.',
          answers: ['-3', 'x=-3', '−3'],
          hint: 'x + 3 means h = −3, and the axis of symmetry is x = h.',
          why: 'h = −3, so the axis of symmetry is x = −3.',
        },
        {
          prompt: 'What is the axis of symmetry of y = (x − 2)² + 7? Enter the value of x.',
          answers: ['2', 'x=2'],
          hint: 'The axis of symmetry passes through the vertex at x = h.',
          why: 'h = 2, so the axis of symmetry is x = 2.',
        },
      ],
    },
    {
      id: 'lc-3',
      title: 'Question 3 of 3',
      prompt: 'Solve x² + 7x + 12 = 0. Enter the two solutions, e.g. -3, -4.',
      answers: ['-3,-4', '-4,-3'],
      hint: 'Find two numbers that multiply to 12 and add to 7.',
      why: 'It factors as (x + 3)(x + 4) = 0, so x = −3 or x = −4.',
      variants: [
        {
          prompt: 'Solve x² + 5x + 6 = 0. Enter the two solutions, e.g. -2, -3.',
          answers: ['-2,-3', '-3,-2'],
          hint: 'Find two numbers that multiply to 6 and add to 5.',
          why: 'It factors as (x + 2)(x + 3) = 0, so x = −2 or x = −3.',
        },
        {
          prompt: 'Solve x² + 6x + 8 = 0. Enter the two solutions, e.g. -2, -4.',
          answers: ['-2,-4', '-4,-2'],
          hint: 'Find two numbers that multiply to 8 and add to 6.',
          why: 'It factors as (x + 2)(x + 4) = 0, so x = −2 or x = −4.',
        },
      ],
    },
  ],
  practiceSteps: [
    {
      id: 'p-vertex',
      type: 'find-vertex',
      title: 'Practice: Find the vertex',
      prompt: 'This graph shows y = (x + 2)² − 1. Drag the dot to the vertex.',
      h: -2,
      k: -1,
      a: 1,
      xMin: -6,
      xMax: 2,
      why: 'h = −2 and k = −1, so the vertex is (−2, −1).',
      hint: 'Find the lowest point of the curve.',
    },
    {
      id: 'p-roots',
      type: 'multiple-choice',
      title: 'Practice: Roots',
      prompt: 'What are the solutions of x² − x − 6 = 0?',
      options: ['x = 3 and x = −2', 'x = 2 and x = 3', 'x = −3 and x = 2', 'x = 6 and x = 1'],
      correctIndex: 0,
      why: 'It factors as (x − 3)(x + 2) = 0, so x = 3 or x = −2.',
      hint: 'Two numbers that multiply to −6 and add to −1.',
    },
  ],
}
